### ISSUE TITLE
Broken docker compose files?

### ISSUE THREAD

**Issue by turulix** [memphisdev/memphis-docker#100]
**Describe the bug**
I have a github action to setup memphis for a testing environment that basically downloads the latest docker-compose file and starts it. This pipeline stopped working apparently due to some changes on newer versions of docker / docker-compose

**To Reproduce**
Download the docker-compose file and try to execute it

**Expected behavior**
It should start

**Screenshots**
![image](https://github.com/memphisdev/memphis-docker/assets/28957605/7eabd286-fb65-46e8-a4be-b141cfa76f3d)

**Additional context**
I don't know when this started happening

**Comment by valeraBr** [comment]
Hi @turulix,

We changed the way the variables are presented in the docker-compose file from:
`- USER_PASS_BASED_AUTH=true`
to 
`USER_PASS_BASED_AUTH: true`.
Can you share the exact way you execute the docker-compose with github actions?

**Comment by turulix** [comment]
Sure the exact step in the workflow is:
https://github.com/turulix/memphis-rust-community/blob/88c298b0bd174cc93282af7082a06ef65f2ae399/.github/workflows/CI.yml#L34-L37

**Comment by valeraBr** [comment]
@turulix 
We changed the way boolean variables are declared. Please check again.

**Comment by turulix** [comment]
That fixed it thank you :)
