### ISSUE TITLE
Leaked Secrets

### ISSUE THREAD

**Issue by Steiner-254** [memphisdev/memphis-docker#29]
~ Hi there, the following secrets were leaked in your repo:
      - JWT_SECRET=35nhvjfosfklgmfg56+fdsgzvfnjksacvbhfksfkgofadsjfgjkoldsdkfvpl’jbgio;dfsjgkl;’XZFVMifobd;dlgjv[sfvjmiodfkvs2fh;fhk44gfdhksdkfdffk
      - REFRESH_JWT_SECRET=35c7b3eb969db065bfa3c66b38e4323e8f73113f3965dfb55c6bc585dcb0ba62bd399e2588fdc8f709ae0b63fb24be32590f134506ca1d7a4314339f11b8045a

**Comment by valeraBr** [comment]
I'm sorry for not getting back to you sooner, those secrets are randomly generated for test purposes only.
We already changed it to avoid misunderstandings. 
Thank you.
